
const GET_FORECAST = "FORECAST/GET";
const CLEAR        = "FORECAST/CLEAR";

const CLEAR_MESSAGE  = "NOTIFICATION/CLEAR";
const UPDATE_MESSAGE = "NOTIFICATION/UPDATE_MESSAGE";

export { CLEAR, GET_FORECAST, CLEAR_MESSAGE, UPDATE_MESSAGE }